title: "Bibliography"
description: "A collection of notes on papers and books. This is experimental."
author: Robert Winslow
remote_theme: RMWinslow/JTD-RMW
search_enabled: true

compress_html:
  ignore:
    envs: all
